name: Coveralls

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Java 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: oracle
        java-version: '17'

    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Test
      run: mvn --quiet test jacoco:report

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.0
