name: Coveralls

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Java 17
      uses: actions/setup-java@v4.2
      with:
        distribution: oracle
        java-version: '17'

    - name: Checkout
      uses: actions/checkout@v4.1

    - name: Test
      run: mvn test jacoco:report

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3
