name: OSSRH

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Setup Java 17
      uses: actions/setup-java@v4.4.0
      with:
        distribution: oracle
        java-version: '17'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Checkout
      uses: actions/checkout@v4.2.1

    - name: Deploy
      run: mvn deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
