name: OSSRH

on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:

    - name: Setup Java 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: oracle
        java-version: '17'
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-private-key: ${{ secrets.PRIVATE_KEY }}
        gpg-passphrase: PASS_PHRASE

    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Deploy
      run: mvn deploy
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        PASS_PHRASE: ${{ secrets.PASS_PHRASE }}
